language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

before_script:
    - composer install --ignore-platform-reqs

script:
  - bin/phpspec run
  - bin/behat
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.xml
